config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :comments
  resources :juries
  resources :locations
  resources :presentations do
    member do
      get :current_page
    end
  end

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :presentation
  belongs_to :jury
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params.require(:mark).permit(:presentation_id, :jury_id, :criterion_1, :criterion_2, :criterion_3, :criterion_4, :criterion_5)
    end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_form.html.erb
<%= form_for @mark, :html => { :class => "form-horizontal mark" } do |f| %>

  <% if @mark.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@mark.errors.count, "error") %> prohibited this mark from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @mark.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :presentation_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :presentation_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:presentation_id) %>
  </div>
  <div class="form-group">
    <%= f.label :jury_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :jury_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:jury_id) %>
  </div>
  <div class="form-group">
    <%= f.label :criterion_1, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :criterion_1, :class => 'form-control' %>
    </div>
    <%=f.error_span(:criterion_1) %>
  </div>
  <div class="form-group">
    <%= f.label :criterion_2, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :criterion_2, :class => 'form-control' %>
    </div>
    <%=f.error_span(:criterion_2) %>
  </div>
  <div class="form-group">
    <%= f.label :criterion_3, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :criterion_3, :class => 'form-control' %>
    </div>
    <%=f.error_span(:criterion_3) %>
  </div>
  <div class="form-group">
    <%= f.label :criterion_4, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :criterion_4, :class => 'form-control' %>
    </div>
    <%=f.error_span(:criterion_4) %>
  </div>
  <div class="form-group">
    <%= f.label :criterion_5, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :criterion_5, :class => 'form-control' %>
    </div>
    <%=f.error_span(:criterion_5) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                marks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/marks/edit.html.erb
<%- model_class = Mark -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/marks/index.html.erb
<%- model_class = Mark -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:presentation_id) %></th>
      <th><%= model_class.human_attribute_name(:jury_id) %></th>
      <th><%= model_class.human_attribute_name(:criterion_1) %></th>
      <th><%= model_class.human_attribute_name(:criterion_2) %></th>
      <th><%= model_class.human_attribute_name(:criterion_3) %></th>
      <th><%= model_class.human_attribute_name(:criterion_4) %></th>
      <th><%= model_class.human_attribute_name(:criterion_5) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @marks.each do |mark| %>
      <tr>
        <td><%= link_to mark.id, mark_path(mark) %></td>
        <td><%= mark.presentation_id %></td>
        <td><%= mark.jury_id %></td>
        <td><%= mark.criterion_1 %></td>
        <td><%= mark.criterion_2 %></td>
        <td><%= mark.criterion_3 %></td>
        <td><%= mark.criterion_4 %></td>
        <td><%= mark.criterion_5 %></td>
        <td><%=l mark.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_mark_path(mark), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      mark_path(mark),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_mark_path,
            :class => 'btn btn-primary' %>

app/views/marks/new.html.erb
<%- model_class = Mark -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/marks/show.html.erb
<%- model_class = Mark -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:presentation_id) %>:</strong></dt>
  <dd><%= @mark.presentation_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:jury_id) %>:</strong></dt>
  <dd><%= @mark.jury_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:criterion_1) %>:</strong></dt>
  <dd><%= @mark.criterion_1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:criterion_2) %>:</strong></dt>
  <dd><%= @mark.criterion_2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:criterion_3) %>:</strong></dt>
  <dd><%= @mark.criterion_3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:criterion_4) %>:</strong></dt>
  <dd><%= @mark.criterion_4 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:criterion_5) %>:</strong></dt>
  <dd><%= @mark.criterion_5 %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              marks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_mark_path(@mark), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              mark_path(@mark),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>