config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :comments
  resources :juries
  resources :locations
  resources :presentations do
    member do
      get :current_page
    end
  end

end

app/models/jury.rb
class Jury < ActiveRecord::Base
  belongs_to :location
end

app/controllers/juries_controller.rb
class JuriesController < ApplicationController
  before_action :set_jury, only: [:show, :edit, :update, :destroy]

  # GET /juries
  # GET /juries.json
  def index
    @juries = Jury.all
  end

  # GET /juries/1
  # GET /juries/1.json
  def show
  end

  # GET /juries/new
  def new
    @jury = Jury.new
  end

  # GET /juries/1/edit
  def edit
  end

  # POST /juries
  # POST /juries.json
  def create
    @jury = Jury.new(jury_params)

    respond_to do |format|
      if @jury.save
        format.html { redirect_to @jury, notice: 'Jury was successfully created.' }
        format.json { render :show, status: :created, location: @jury }
      else
        format.html { render :new }
        format.json { render json: @jury.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /juries/1
  # PATCH/PUT /juries/1.json
  def update
    respond_to do |format|
      if @jury.update(jury_params)
        format.html { redirect_to @jury, notice: 'Jury was successfully updated.' }
        format.json { render :show, status: :ok, location: @jury }
      else
        format.html { render :edit }
        format.json { render json: @jury.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /juries/1
  # DELETE /juries/1.json
  def destroy
    @jury.destroy
    respond_to do |format|
      format.html { redirect_to juries_url, notice: 'Jury was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jury
      @jury = Jury.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jury_params
      params.require(:jury).permit(:name, :location_id)
    end
end

app/helpers/juries_helper.rb
module JuriesHelper
end

app/views/juries/_form.html.erb
<%= form_for @jury, :html => { :class => "form-horizontal jury" } do |f| %>

  <% if @jury.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@jury.errors.count, "error") %> prohibited this jury from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @jury.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :location_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                juries_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/juries/edit.html.erb
<%- model_class = Jury -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/juries/index.html.erb
<%- model_class = Jury -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @juries.each do |jury| %>
      <tr>
        <td><%= link_to jury.id, jury_path(jury) %></td>
        <td><%= jury.name %></td>
        <td><%= jury.location_id %></td>
        <td><%=l jury.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_jury_path(jury), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      jury_path(jury),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_jury_path,
            :class => 'btn btn-primary' %>

app/views/juries/new.html.erb
<%- model_class = Jury -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/juries/show.html.erb
<%- model_class = Jury -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @jury.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location_id) %>:</strong></dt>
  <dd><%= @jury.location_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              juries_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_jury_path(@jury), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              jury_path(@jury),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>