config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :comments
  resources :juries
  resources :locations
  resources :presentations do
    member do
      get :current_page
    end
  end

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  belongs_to :location
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    render @current_template
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render :index, status: :created, location: @presentation }
      else
        format.html { render :new }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { render :index, status: :ok, location: @presentation }
      else
        format.html { render :edit }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def current_page
    @presentation = Presentation.find(params[:id])
    new_page = params[:page]
    if(new_page)
      @presentation.page = new_page
      @presentation.save
    end

    respond_to do |format|
      format.json { render json: {page: @presentation.page}, status: :ok }
    end
  end

  def set_current_page
    byebug
    @presentation = Presentation.find(params[:id])
    new_page = params[:page]
    @presentation.page = new_page
    @presentation.save
    
    respond_to do |format|
      format.json { render json: {page: @presentation.page}, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
      @jury = Jury.find params[:jury_id] rescue nil
      @current_template = @jury ? :jury : :show
      @pages = Dir.entries("public/pdf/#{@presentation.path}") - ['.', '..']
      @pages.sort!
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:name, :path, :authors, :location_id, :number, :page, :is_active)
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<%= form_for @presentation, :html => { :class => "form-horizontal presentation" } do |f| %>

  <% if @presentation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@presentation.errors.count, "error") %> prohibited this presentation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @presentation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :path, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :path, :class => 'form-control' %>
    </div>
    <%=f.error_span(:path) %>
  </div>
  <div class="form-group">
    <%= f.label :authors, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :authors, :class => 'form-control' %>
    </div>
    <%=f.error_span(:authors) %>
  </div>
  <div class="form-group">
    <%= f.label :location_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location_id) %>
  </div>
  <div class="form-group">
    <%= f.label :number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:number) %>
  </div>
  <div class="form-group">
    <%= f.label :page, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :page, :class => 'form-control' %>
    </div>
    <%=f.error_span(:page) %>
  </div>
  <div class="form-group">
    <%= f.label :is_active, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :is_active, :class => 'form-control' %>
    </div>
    <%=f.error_span(:is_active) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                presentations_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/presentations/edit.html.erb
<%- model_class = Presentation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/presentations/index.html.erb
<%- model_class = Presentation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:path) %></th>
      <th><%= model_class.human_attribute_name(:authors) %></th>
      <th><%= model_class.human_attribute_name(:location_id) %></th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:page) %></th>
      <th><%= model_class.human_attribute_name(:is_active) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @presentations.each do |presentation| %>
      <tr>
        <td><%= link_to presentation.id, presentation_path(presentation) %></td>
        <td><%= presentation.name %></td>
        <td><%= presentation.path %></td>
        <td><%= presentation.authors %></td>
        <td><%= presentation.location_id %></td>
        <td><%= presentation.number %></td>
        <td><%= presentation.page %></td>
        <td><%= presentation.is_active %></td>
        <td><%=l presentation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_presentation_path(presentation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      presentation_path(presentation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_presentation_path,
            :class => 'btn btn-primary' %>

app/views/presentations/jury.html.erb
<%- model_class = Presentation -%>
<div class="header">
  <strong>Член жюри:</strong> <%= @jury.name %> - 
  <strong><%= @presentation.name %></strong> - 
  Страница <strong><span id="page_number" name="page_number"><%= @presentation.page %></span></strong>
</div>

<div class="content" data-page="<%= @presentation.page %>" data-max-page="<%= @pages.size %>" data-presentation-id="<%= @presentation.id %>">
  <% @pages.each_with_index do |filename, page| %>
    <%= image_tag "/pdf/#{@presentation.path}/#{filename}", class: (page != @presentation.page - 1) ? 'hidden' : '' %>
  <% end %>
</div>

<div class="footer">
  <%= link_to 'Назад', '#', class: 'btn btn-default back' %>
  <%= link_to 'К докладчику', '#', class: 'btn btn-default sync' %>
  <%= link_to 'Дальше', '#', class: 'btn btn-default next' %>
</div>

app/views/presentations/new.html.erb
<%- model_class = Presentation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/presentations/show.html.erb
<div class="header">
  <strong><%= @presentation.name %></strong> - 
  Страница <strong><span id="page_number" name="page_number"><%= @presentation.page %></span></strong>
</div>

<div class="content" data-page="<%= @presentation.page %>" data-max-page="<%= @pages.size %>" data-presentation-id="<%= @presentation.id %>">
  <% @pages.each_with_index do |filename, page| %>
    <%= image_tag "/pdf/#{@presentation.path}/#{filename}", class: (page != @presentation.page - 1) ? 'hidden' : '' %>
  <% end %>
</div>

<div class="footer">
  <%= link_to 'Назад', '#', class: 'btn btn-default step-back' %>
  <%= link_to 'Закончить', '#', class: 'btn btn-default end' %>
  <%= link_to 'Дальше', '#', class: 'btn btn-default step-next' %>
</div>